###############################################################
#           WAVE integration config file
# Defines variable parameters required to run integration
# Needs to be kept up-to-date by user
###############################################################
WEAP:
  Area: WAVE-SyrDarya 2022_09_19_MABIA
  Branches:
    Population_KAZ:
      path: Key\Demographic\KAZ\National population
      variable: Annual Activity Level
      unit: cap
      leap_branch: Population 
      leap_region: Kazakhstan
    Population_KGZ:
      path: Key\Demographic\KAZ\National population
      variable: Annual Activity Level
      unit: cap
      leap_branch: Population
      leap_region: Kyrgyzstan
    Population_TJK:
      path: Key\Demographic\KAZ\National population
      variable: Annual Activity Level
      unit: cap
      leap_branch: Population
      leap_region: Tajikistan
    Population_UZB:
      path: Key\Demographic\KAZ\National population
      variable: Annual Activity Level
      unit: cap
      leap_branch: Population
      leap_region: Uzbekistan
    GDP_KAZ:
      path: Key\Macroeconomic\KAZ\GDP
      variable: Annual Activity Level
      unit: Billion 2020 USD
      leap_branch: GDP
      leap_region: Kazakhstan
    GDP_KGZ:
      path: Key\Macroeconomic\KGZ\GDP
      variable: Annual Activity Level
      unit: Billion 2020 USD
      leap_branch: GDP
      leap_region: Kyrgyzstan
    GDP_TJK:
      path: Key\Macroeconomic\TJK\GDP
      variable: Annual Activity Level
      unit: Billion 2020 USD
      leap_branch: GDP
      leap_region: Tajikistan
    GDP_UZB:
      path: Key\Macroeconomic\UZB\GDP
      variable: Annual Activity Level
      unit: Billion 2020 USD
      leap_branch: GDP
      leap_region: Uzbekistan
    Industrial_VA_KAZ:
      path: Key\Macroeconomic\KAZ\Industrial value added
      variable: Annual Activity Level
      unit: '% share'
      leap_branch: GDP
      leap_branch: Industrial_VA_fraction
      leap_region: Kazakhstan
    Industrial_VA_KGZ:
      path: Key\Macroeconomic\KGZ\Industrial value added
      variable: Annual Activity Level
      unit: '% share'
      leap_branch: Industrial_VA_fraction
      leap_region: Kyrgyzstan
    Industrial_VA_TJK:
      path: Key\Macroeconomic\TJK\Industrial value added
      variable: Annual Activity Level
      unit: '% share'
      leap_branch: Industrial_VA_fraction
      leap_region: Tajikistan
    Industrial_VA_UZB:
      path: Key\Macroeconomic\UZB\Industrial value added
      variable: Annual Activity Level
      unit: '% share'
      leap_branch: Industrial_VA_fraction
      leap_region: Uzbekistan


  Hydropower_plants:
    convergence_check:
        weap_variable: Hydropower Generation # WEAP result variable to be checked for convergence
        weap_unit: GWH
    dams:
        Toktogul:
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Toktogul reservoir
          leap_hpps : [TOKTOGUL]
        Kambarata_I:
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Kambarata_I
          leap_hpps : [KAMBARATA_1]
        Kambarata_II:
          weap_path : Supply and Resources\River\Syr Darya River\Run of River Hydro\Kambarata II
          leap_hpps : [KAMBARATA_2]
        Kayrakkum :
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Kayrakkum reservoir
          leap_hpps : [KAIRAKKUM]
        Shardara :
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Shardara reservoir
          leap_hpps : [SHARDARINSKYA]
        Kurpsaiskaja:
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Kurpsaiskaja
          leap_hpps : [KURPSAI]
        Taschkumyrskaja : 
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Taschkumyrskaja_cascade
          leap_hpps : [TASH_KUMYR, SHAMALDYSAI,UCH_KURGANSK]
        Farkhad : 
          weap_path : Supply and Resources\River\Syr Darya River\Reservoirs\Farkhad reservoir
          leap_hpps : [FARKHAD]
        Akhangaran : 
          weap_path : Supply and Resources\River\Ahangaran\Reservoirs\Akhangaran reservoir
          leap_hpps: [AKHANGARAN]
        Charvak: 
          weap_path : Supply and Resources\River\Circik River\Reservoirs\Charvak reservoir
          leap_hpps : [CHARVAK, GAZLKENT, KHODZHIKENT]
        Chirchik:
          weap_path : Supply and Resources\River\Circik River\Reservoirs\Chirchik_cascade
          leap_hpps : [AKKAVAK_1, CHIRCHIK_1, CHIRCHIK_2, TAVAK]
        Andijan :
          weap_path : Supply and Resources\River\Andijan River\Reservoirs\Andijan Reservoir
          leap_hpps : [ANDIJAN_1, ANDIJAN_2]
        At-Bashi : 
          weap_path : Supply and Resources\River\Syr Darya River\Run of River Hydro\At Bashi RoR
          leap_hpps : [AT_BASHIN]
        Kokomeren : 
          weap_path : Supply and Resources\River\Kokomeren River\Run of River Hydro\Kokomeren RoR
          leap_hpps : [KOKOMEREN]
        Upper Naryn : 
          weap_path : Supply and Resources\River\Syr Darya River\Run of River Hydro\Upper Naryn RoR
          leap_hpps : [UPPER NARYN]
        Kazarman : 
          weap_path : Supply and Resources\River\Syr Darya River\Run of River Hydro\Kazarman RoR
          leap_hpps : [KAZARMAN]

  Agricultural regions: # these are used for water pumping
    Kazakhstan:
      Kyzlorda:
        weap_path : Demand Sites and Catchments\Agriculture_KAZ_Kyzylorda 
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
      Shmykent:
        weap_path: Demand Sites and Catchments\Agriculture_KAZ_Turkestan_Shymkent
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
    Kyrgyzstan:
      JalalAbat:
        weap_path: Demand Sites and Catchments\Agriculture_KGZ_Naryn_JalalAbat_Osh_Batken
        leap_region: Kyrgyzstan
        variable: Supply Requirement
        unit: m^3
    Tajikistan:
      Sogd:
        weap_path: Demand Sites and Catchments\Agriculture_TJK_Sogd
        leap_region: Tajikistan
        variable: Supply Requirement
        unit: m^3
    Uzbekistan:
      Andijan:
        weap_path: Demand Sites and Catchments\Agriculture_UZB_Andijan_Namangan_Fergana
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: m^3
      SyrDarya:
        weap_path: Demand Sites and Catchments\Agriculture_UZB_SyrDarya_Tashkent_Jizzakh
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: 'm^3'
  
  Industrial and domestic regions: # these are used for water pumping
    Kazakhstan:
      Kyzlorda_Ind:
        weap_path : Demand Sites and Catchments\Industrial_KAZ_Kyzylorda 
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
      Shmykent_Ind:
        weap_path: Demand Sites and Catchments\Industrial_KAZ_Turkestan_Shymkent
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
      Kyzlorda_Dom:
        weap_path : Demand Sites and Catchments\Domestic_KAZ_Kyzylorda 
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
      Shmykent_Dom:
        weap_path: Demand Sites and Catchments\Domestic_KAZ_Turkestan_Shymkent
        leap_region: Kazakhstan
        variable: Supply Requirement
        unit: m^3
    Kyrgyzstan:
      JalalAba_Ind:
        weap_path: Demand Sites and Catchments\Industrial_KGZ_Naryn_JalalAbat_Osh_Batken
        leap_region: Kyrgyzstan
        variable: Supply Requirement
        unit: m^3
      JalalAbat_Dom:
        weap_path: Demand Sites and Catchments\Domestic_KGZ_Naryn_JalalAbat_Osh_Batken
        leap_region: Kyrgyzstan
        variable: Supply Requirement
        unit: m^3
    Tajikistan:
      Sogd_Ind:
        weap_path: Demand Sites and Catchments\Industrial_TJK_Sogd
        leap_region: Tajikistan
        variable: Supply Requirement
        unit: m^3
      Sogd_Dom:
        weap_path: Demand Sites and Catchments\Domestic_TJK_Sogd
        leap_region: Tajikistan
        variable: Supply Requirement
        unit: m^3
    Uzbekistan:
      Andijan_Ind:
        weap_path: Demand Sites and Catchments\Industrial_UZB_Andijan_Namangan_Fergana
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: m^3
      SyrDarya_Ind:
        weap_path: Demand Sites and Catchments\Industrial_UZB_SyrDarya_Tashkent_Jizzakh
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: m^3
      Andijan_Dom:
        weap_path: Demand Sites and Catchments\Domestic_UZB_Andijan_Namangan_Fergana
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: m^3
      SyrDarya_Dom:
        weap_path: Demand Sites and Catchments\Domestic_UZB_SyrDarya_Tashkent_Jizzakh
        leap_region: Uzbekistan
        variable: Supply Requirement
        unit: m^3


LEAP:
  Area: wave central asia v43
  Regions: [Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan]
  # Folder for storing Excel files with WEAP outputs for hydropower plants used by LEAP as inputs
  # This must be at the same level as the "LEAP Areas" folder, and will be created if it does not exist
  Folder: WAVE_Hydro
  # These are month names as specified in time slices; they should start with January and go through December
  Months: [January, February, March, April, May, June, July, August, September, October, November, December]
  Branches: 
    GDP:
      path: Key\Macroeconomic\Gross Domestic Product
      variable: Activity Level
      unit: 2020 USD
    Population: 
      path: Key\Demographic\Population
      variable: Activity Level
      unit: people
    Industrial_VA_fraction:
      path: Key\Macroeconomic\Industrial\Industry_Value Added Fraction
      variable: Activity Level
      unit: Fraction
    Industrial VA:
      path: Key\Macroeconomic\Industrial_Value Added
      variable: Activity Level
      unit: 2020 USD
    Commercial VA:
      path: Key\Macroeconomic\Commercial_Value Added
      variable: Activity Level
      unit: 2020 USD
    Agricultural VA:
      path: Key\Macroeconomic\Agriculture_Value Added
      variable: Activity Level
      unit: 2020 USD
    Ag_water_demand:
      path: Demand\Agriculture\Syr Darya\Water demand
      variable: Activity Level
      unit: Cubic Meter/No Data
    Ind_water_demand:
      path: Demand\Industry\Other\Syr Darya Water Pumping
      variable: Activity Level
      unit: Cubic Meter/No Data
  
  Hydropower_plants:
    convergence_check:
        leap_variable: Energy Generation # LEAP result to be checked for convergence
        leap_unit: GWh
    plants:
        AKHANGARAN:
          leap_path: Transformation\Electricity Production\Processes\AKHANGARAN RESERVOIR
          leap_region: Uzbekistan
        ANDIJAN_1: 
          leap_path: Transformation\Electricity Production\Processes\ANDIJAN_1
          leap_region: Uzbekistan
        AKKAVAK_1:
          leap_path: Transformation\Electricity Production\Processes\AKKAVAK_1
          leap_region: Uzbekistan
        ANDIJAN_2: 
          leap_path: Transformation\Electricity Production\Processes\ANDIJAN_2
          leap_region: Uzbekistan
        AT_BASHIN:
          leap_path: Transformation\Electricity Production\Processes\AT_BASHIN
          leap_region: Kyrgyzstan
        CHARVAK:
          leap_path: Transformation\Electricity Production\Processes\CHARVAK
          leap_region: Uzbekistan
        CHIRCHIK_1:
          leap_path: Transformation\Electricity Production\Processes\CHIRCHIK_1
          leap_region: Uzbekistan
        CHIRCHIK_2:
          leap_path: Transformation\Electricity Production\Processes\CHIRCHIK_2
          leap_region: Uzbekistan
        FARKHAD: 
          leap_path : Transformation\Electricity Production\Processes\FARKHAD
          leap_region: Uzbekistan
        GAZLKENT:
          leap_path: Transformation\Electricity Production\Processes\GAZALKENT
          leap_region: Uzbekistan
        KAIRAKKUM:
          leap_path: Transformation\Electricity Production\Processes\KAIRAKKUM
          leap_region: Tajikistan
        KAMBARATA_1:
          leap_path: Transformation\Electricity Production\Processes\KAMBARATA_1
          leap_region: Kyrgyzstan
        KAMBARATA_2:
          leap_path: Transformation\Electricity Production\Processes\KAMBARATA_2
          leap_region: Kyrgyzstan
        KHODZHIKENT:
          leap_path: Transformation\Electricity Production\Processes\KHODZHIKENT
          leap_region: Uzbekistan
        KURPSAI:
          leap_path: Transformation\Electricity Production\Processes\KURPSAI
          leap_region: Kyrgyzstan
        SHAMALDYSAI:
          leap_path: Transformation\Electricity Production\Processes\SHAMALDYSAI
          leap_region: Kyrgyzstan
        SHARDARINSKYA:
          leap_path: Transformation\Electricity Production\Processes\SHARDARINSKYA
          leap_region: Kazakhstan
        TASH_KUMYR:
          leap_path: Transformation\Electricity Production\Processes\TASH_KUMYR
          leap_region: Kyrgyzstan
        TAVAK:
          leap_path: Transformation\Electricity Production\Processes\TAVAK
          leap_region: Uzbekistan
        TOKTOGUL:
          leap_path: Transformation\Electricity Production\Processes\TOKTOGUL
          leap_region: Kyrgyzstan
        UCH_KURGANSK:
          leap_path: Transformation\Electricity Production\Processes\UCH_KURGANSK
          leap_region: Kyrgyzstan
        KOKOMEREN:
          leap_path: Transformation\Electricity Production\Processes\SUUSAMYR_KOKOMEREN CASCADE
          leap_region: Kyrgyzstan
        UPPER NARYN:
          leap_path: Transformation\Electricity Production\Processes\UPPER NARYN CASCADE
          leap_region: Kyrgyzstan
        KAZARMAN:
          leap_path: Transformation\Electricity Production\Processes\KAZARMAN CASCADE
          leap_region: Kyrgyzstan

LEAP-Macro: # Removing this will stop wave-integration from running with leap-macro
  # Main folder for Macro models
  # This must be at the same level as the "LEAP Areas" folder. It will be created if it does not exist, but it must
  # exist and have the named directories listed below.
  Folder: WAVE_Macro
  # Target variables are the same for each region: must match branches in LEAP config above
  LEAP:
    target_variables : [GDP, Industrial VA, Commercial VA, Agricultural VA]
  WEAP:
    agsector: Agriculture_
    price_data: crop_prices.csv
    cov_to_util_exponent: 0.2
    all_crops: &WEAP_CROPS
      - Apples
      - Barley
      - Corn
      - Cotton
      - Grapes
      - Oil seeds and pulses
      - Other crops
      - Other grains
      - Other orchards
      - Potatoes
      - Rice
      - Sugar beet
      - Vegetables
      - Watermelons and squash
      - Wheat
  Regions:
      # Kazakhstan:
        # directory_name: KAZ_Macro
        # script: runleapmacro.jl
        # weap_region: [KAZ]
        # weap_coverage_mapping: 
          # Agriculture_: [S_agfor]
          # Industrial_: [S_food, S_paperpulp, S_otherind]
          # Domestic_: [S_hotelrestaurant, S_otherserv]
        # weap_crop_production_mapping:
          # Agriculture_:
            # value: [S_agfor]
            # real_index:
                # All crops: [S_agfor]
        # weap_price_index_mapping: 
          # Agriculture_:
            # Seasonal crops: [P_agforseasonal]
            # Perennial crops: [P_agforperennial]
        # crop_categories:
          # Perennial crops:
              # - Apples
              # - Grapes
              # - Other orchards
          # Seasonal crops:
              # - Barley
              # - Corn
              # - Cotton
              # - Oil seeds and pulses
              # - Other crops
              # - Other grains
              # - Potatoes
              # - Rice
              # - Sugar beet
              # - Vegetables
              # - Watermelons and squash
              # - Wheat
      # Kyrgyzstan:
        # directory_name: KGZ_Macro
        # script: runleapmacro.jl
        # weap_region: [KGZ]
        # weap_coverage_mapping: 
          # Agriculture_: [S_agfor]
          # Industrial_: [S_food, S_woodpaper, S_otherind]
          # Domestic_: [S_hotelrestaurant, S_otherserv]
        # weap_crop_production_mapping:
          # Agriculture_:
            # value: [S_agfor]
            # real_index:
                # All crops: [S_agfor]
        # weap_price_index_mapping: 
          # Agriculture_: 
            # All crops: [P_agfor]
        # crop_categories:
          # All crops: *WEAP_CROPS
      Uzbekistan:
        directory_name: UZB_Macro
        script: runleapmacro.jl
        weap_region: [UZB]
        weap_coverage_mapping: 
          Agriculture_: [Acotton,Agrain,Atomat,Avegat,Afruit,Agrape,Apotat,AothA]
          Industrial_: [Ametal,Achem,Amach,Aginning,Atextile,Amilling,Afood,AothI]
          Domestic_: [Acons,Atrad,Atrans,Aots]
        # weap_crop_production_mapping:
          # Agriculture_:
            # value: [Acotton,Agrain,Atomat,Avegat,Afruit,Agrape,Apotat,AothA,Aanim]
            # real_index:
                # All crops: [Acotton,Agrain,Atomat,Avegat,Afruit,Agrape,Apotat,AothA,Aanim]
        # weap_price_index_mapping: 
          # Agriculture_:
            # Cotton: [Ccotton]
            # Grains: [Cgrain]
            # Vegetables: [Ctomat,Cvegat]
            # Potatoes: [Cpotat]
            # Fruits: [Cfruit]
            # Grapes: [Cgrape]
            # Other crops: [CothA]
        crop_categories:
         Cotton:
            weap: [Cotton]
            macro: {sector: [Acotton], product: [Ccotton]}
         Grains:
            weap: [Barley,Corn,Rice,Wheat,Other grains]
            macro: {sector: [Agrain], product: [Cgrain]}
         Vegetables:
            weap: [Vegetables]
            macro: {sector: [Atomat,Avegat], product: [Ctomat,Cvegat]}
         Potatoes:
            weap: [Potatoes]
            macro: {sector: [Apotat], product: [Cpotat]}
         Fruits:
            weap: [Apples,Other orchards]
            macro: {sector: [Afruit], product: [Cfruit]}
         Grapes:
            weap: [Grapes]
            macro: {sector: [Agrape], product: [Cgrape]}
         Other crops:
            weap: [Oil seeds and pulses,Sugar beet,Watermelons and squash,Other crops]
            macro: {sector: [AothA,Aanim], product: [CothA]}
        # crop_categories:
         # Cotton:
              # - Cotton
         # Grains:
              # - Barley
              # - Corn
              # - Rice
              # - Wheat
              # - Other grains
         # Vegetables:
              # - Vegetables
         # Potatoes:
              # - Potatoes
         # Fruits:
              # - Apples
              # - Other orchards
         # Grapes:
              # - Grapes
         # Other crops:
              # - Oil seeds and pulses
              # - Sugar beet
              # - Watermelons and squash
              # - Other crops
